### ISSUE TITLE
Replace LLVM's DSA with sea-dsa

### ISSUE THREAD

**Issue by shaobo-he** [smackers/smack#549]
This issue is used to keep track of the issues we have during the transition.

- [x] Add license/acknowledgement
- [x] Resolve indirect calls using sea-dsa (reference: https://github.com/seahorn/seahorn/pull/269)
- [x] Failing regression: test/c/basic/atomic_cas.c (https://github.com/seahorn/sea-dsa/issues/53) Sol: move it to failing.
- [x] Failing regression: test/c/basic/extern_mem_fail.c (https://github.com/seahorn/sea-dsa/issues/63) Sol: document design decision; move it to failing; add an option like `no-external` that make this sound.
- [x] Failing regression: test/c/data/pointers5.c (https://github.com/seahorn/sea-dsa/issues/62)
- [x] Failing regression: test/c/memory-safety/global_and_heap_alloc_fail_no_free.c
- [x] Unknown regression: test/c/memory-safety/null_dereference_fail.c Sol: move it to failing; add some notes.
- [x] Figure out if the type safety pass is necessary
- [x] Fix the build process
- [x] Remove the dependency of subversion
- [x] Do not install libSeaDsaAnalysis.a
- [x] Figure out print dsa graph (create an issue)
- [x] Figure out why we can't handle large offsets

**Comment by zvonimir** [comment]
@shaobo-he Your last check-mark is still not done it seems. Is that right?
What should we do about this?

**Comment by shaobo-he** [comment]
> @shaobo-he Your last check-mark is still not done it seems. Is that right?
> What should we do about this?

Let me create a new issue for it and then remove it from this issue.
